### ISSUE TITLE
Oid of authorInstitution in Metadata must point to SOR

### ISSUE THREAD

**Issue by jonigkeit** [scandihealth/lpr3-docs#102]
The XDR interface wrongfully expects an CVR identifier in the authorInstition of the XDS Metadata.
It should expect SOR identifiers as set forth by [XDS Metadata for Document Sharing Danish Profile](http://svn.medcom.dk/svn/drafts/Standarder/IHE/DK_profil_metadata/Metadata-v095.docx).

The examples and the server-side validation need to be updated.
Once in place, integrators will have to send SOR identifiers instead of CVR.

**Comment by jkiddo** [comment]
Example has been updated: 5bb9908 and authorities have been notified about the misguiding example in the underlying specification

**Comment by TueCN** [comment]
**RESOLUTION**
Now XDS metadata `authorInstitution` is no longer expected to be a CVR number

**Comment by CgiMofr** [comment]
Hi,
We have changed our submissions and now send correct XON data. But still get errors. We have tried with what we think is correct:
![image](https://user-images.githubusercontent.com/39047490/46064499-d5f60180-c16f-11e8-9a30-4da3f16f052c.png)

(NOTE: the xml we send is in one line, and the newline between 'Region' and 'Nordjylland' is not sent)

and which gives the error:

INTEGRITY_CHECK|||The submission set must have an ihe-xdr Classification/Slot element with an authorInstitution attribute|||AUTHOR_INSTITUTION_NOT_FOUND"

The last thing we tried was:
![image](https://user-images.githubusercontent.com/39047490/46064564-ffaf2880-c16f-11e8-8e43-40dfddcf0bfa.png)

with just '&' instead of &amp;, as the example in the document. This is however bad xml, 
and we get the error:

<faultstring>Problems creating SAAJ object model</faultstring>.

We cant see what causes the problem ?
