### ISSUE TITLE
INTEGRITY_CHECK MYNDIGHED_CODE_NOT_FOUND

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#103]
We get the following response from our CDA submission. Does the string used for the ClinicalDocument/setId/*assigningAuthorityName need to be a known value. We would expect to send the same thing for every document, but let us know if their is an expectation for this value. The actual CDA document we are submitting is in the attached file.
[INTEGRITY_CHECK_issue_1.zip](https://github.com/scandihealth/lpr3-docs/files/1961165/INTEGRITY_CHECK_issue_1.zip)

```XML
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
	<Header>
		<ep2:Header xmlns:ep2="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd">
			<ep2:SecurityLevel>3</ep2:SecurityLevel>
			<ep2:TimeOut></ep2:TimeOut>
			<ep2:Linking>
				<ep2:MessageID>950950950-106770-6476862399</ep2:MessageID>
			</ep2:Linking>
			<ep2:FlowStatus>flow_finalized_succesfully</ep2:FlowStatus>
			<ep2:RequireNonRepudiationReceipt>no</ep2:RequireNonRepudiationReceipt>
		</ep2:Header>
	</Header>
	<Body>
		<ep5:RegistryResponse xmlns:ep5="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure">
			<ep5:RegistryErrorList highestSeverity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error">
				<ep5:RegistryError codeContext="INTEGRITY_CHECK|||MYNDIGHED_CODE_NOT_FOUND|||Myndighedskode DaneTranslated not found in the registry|||DaneTranslated" errorCode="InvalidDocumentContent" location="2067EFBE-DC36-11E7-B7F3-0050568B7405^A992159C-44C0-11E8-9061-0050568B7405|||//*[@*='DaneTranslated']" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"></ep5:RegistryError>
			</ep5:RegistryErrorList>
		</ep5:RegistryResponse>
	</Body>
	<MessageProperties xmlns="urn:epic-com:Interconnect.2011.Services">
		<HTTPHeaders>
			<Connection>keep-alive</Connection>
			<Transfer-Encoding>chunked</Transfer-Encoding>
			<Content-Type>multipart/related; type="application/xop+xml"; boundary="uuid:505c336c-7314-40ad-9286-eeefc5c31955"; start="&lt;root.message@cxf.apache.org&gt;"; start-info="text/xml"</Content-Type>
			<Date>Mon, 30 Apr 2018 15:19:59 GMT</Date>
			<Server>WildFly/10</Server>
			<X-Powered-By>Undertow/1</X-Powered-By>
		</HTTPHeaders>
		<StatusCode>OK</StatusCode>
		<StatusCodeNumber>200</StatusCodeNumber>
		<StatusDescription>OK</StatusDescription>
		<ContentType>multipart/related; type="application/xop+xml"</ContentType>
		<MediaType>multipart/related</MediaType>
	</MessageProperties>
</Envelope>
```

**Comment by TueCN** [comment]
As reported by the error, the problem is with the value `DaneTranslated` entered in the `county` element of the patient address.

When providing an address for a patient, the information is mapped to the UofficielBopæl element on [the logical model](https://scandihealth.github.io/lpr3-docs/img/LPR3.png). The county element in the submission is mapped to `kommuneKode` which has datatype `MynKod`

The MynKod type represents `MYNKOD` values in the Danish "authority" registry: [CPR's myndighedsregister](https://www.cpr.dk/kunder/gratis-download/myndighedsregister-og-udtraeksbeskrivelse/), which are 4 digit numbers that are codes for all "authorities" in Denmark,  including municipality entities. 
![image](https://user-images.githubusercontent.com/14910711/39449561-b5a17cb4-4cc8-11e8-89bd-d66864931263.png)

Although any MYNKOD value can be entered in the county field, the intention is that the value should be the code for the Danish municipality where the patient lives.

For example, I believe the MYNKOD value for Aarhus Kommune is `0751`
