### ISSUE TITLE
org.hibernate.exception.DataException: could not extract ResultSet

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#147]
**This issue are blocking**

When we are sending the following CDA document we got the following answer from PatientHealthcareReportingService:
```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">Call failed on the server. Error has been logged to the server log and database: org.hibernate.exception.DataException: could not extract ResultSet</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

CDA Document: 
[cda_document.txt](https://github.com/scandihealth/lpr3-docs/files/2180097/cda_document.txt)

**Comment by JacobBangSSE** [comment]
Do you have an update on this issue? It is impossible for us to debug the issue when the server just returns an useless error message.

**Comment by TueCN** [comment]
Hi,

The exception occurs when sending a document containing SKS code values that are too long (more than 11 characters).

In the attached document the codes `SST:SKS.a.admALDB00` and `SST:SKS.a.admALDA30` are used, but they are not valid SKS code values (they are too long).

We will look into making the service return a `SKS_CODE_NOT_FOUND` INTEGRITY_CHECK error instead of throwing a runtime exception.

In the mean time, you can work around the issue by using a valid SKS code (or an invalid code with a max length of 11)

**Comment by TueCN** [comment]
**RESOLUTION**
An INTEGRITY_CHECK error is now returned by the service when the submitted document has SKS code values longer than 11 characters
