### ISSUE TITLE
Nullpointer exception - known cause

### ISSUE THREAD

**Issue by Remcovanderwerf** [scandihealth/lpr3-docs#160]
Hi,

I was testing with some different messages, trying to get past some Integrity_Checks and got the following error:
sending: 
[CDA_error.txt](https://github.com/scandihealth/lpr3-docs/files/2280504/CDA_error.txt)

which gives me the following java nullpointer error:
[java_error.txt](https://github.com/scandihealth/lpr3-docs/files/2280505/java_error.txt)

send date/time: Sat Aug 11 21:56:39 

When i send:
[CDA_no_error.txt](https://github.com/scandihealth/lpr3-docs/files/2280491/CDA_no_error.txt)
i get the error
`ns2:RegistryError codeContext="INTEGRITY_CHECK|||SKS kode 6101000016001 not found from 2018-03-09T13:41+01:00 to 2018-03-09T13:56+01:00|||SKS_CODE_NOT_FOUND|`

difference in the CDA files:
I changed the SKS code from 6101000016001 to ALFB03  (to get past the integrity check above) because apparently the given 6101000016001 is completely wrong.
templateID: 1.2.208.176.7.1.10.8  (parent templateId:  1.2.208.176.7.1.10.7) 

What can be the cause of this? Or am I missing something?

Looking forward hearing from you!

Kind regards,

Remco van der Werf
VANAD Enovation | The Netherlands
Contractor: Region Syddanmark

**Comment by TueCN** [comment]
The NullPointerException happens because `ClinicalDocument/effectiveTime` does not have an attribute `value`, which it must have according to [art-decor](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.71&effectiveDate=2018-01-04T00:00:00)

This rule has always been in effect, but was just recently specified on art-decor in relation to resolving issue #154. 
The updated rule has not been deployed yet, but when it is deployed you should receive a SCHEMATRON error instead of a NullPointerException.

The reason that [CDA_no_error.txt](https://github.com/scandihealth/lpr3-docs/files/2280491/CDA_no_error.txt) does not cause a NullPointerException is that INTEGRITY_CHECK errors halts the validation execution, before the value in `effectiveTime` is procesed.

So to fix your problem, you must specify a value. 
Example: `<effectiveTime value="20180813090717+0200"/>`

**Comment by Remcovanderwerf** [comment]
Hi,

Implemented in CDA, tested and it works.
I guess the reason I missed it was in fact because it was missing in the template before.

Thank you for the response and the help, closing the issue.

**Comment by TueCN** [comment]
**RESOLUTION**
The updated Schematron rules regarding mandatory ClinicalDocument/effectiveTime have now been deployed
