### ISSUE TITLE
problems with register LPR3 since last week

### ISSUE THREAD

**Issue by cgisbp** [scandihealth/lpr3-docs#161]
Hi, we have problem with sending since last week.

We don't use Soap-UI

Please help us

[Lpr3doc01.txt](https://github.com/scandihealth/lpr3-docs/files/2282347/Lpr3doc01.txt)

**Comment by TueCN** [comment]
We have reproduced the error and will look into the cause. 

In the mean time, you can work around this problem by using the PatientHealthcareValidateReportingService endpoint instead.

**Comment by cgisbp** [comment]
We tried again few minutes ago with PatientHealthcareReportingService and got an other error.

[Lpr3doc02.txt](https://github.com/scandihealth/lpr3-docs/files/2282959/Lpr3doc02.txt)

**Comment by TueCN** [comment]
https://github.com/scandihealth/lpr3-docs/issues/161#issuecomment-412505717: I get a `javax.ejb.EJBTransactionRolledbackException: Transaction rolled back` using [Lpr3doc02.txt](https://github.com/scandihealth/lpr3-docs/files/2282959/Lpr3doc02.txt), not a `NullPointerException`.

The reason you no longer see the `org.hibernate.exception.GenericJDBCException: could not extract ResultSet` is because of the fix from https://github.com/scandihealth/lpr3-docs/issues/159#issuecomment-412475359

**Comment by TueCN** [comment]
We have identified the problem causing the `Transaction rolled back` error and expect it to be resolved today, end of day latest. 
I will post an update when it is resolved.

**Comment by TueCN** [comment]
**RESOLUTION**
Database configuration error was preventing submissions with Encounters containing a DK Payment Contract Act ("betalingsoplysning") from being persisted.

**Comment by cgisbp** [comment]
We have found an other case with ERROR-500

[Lpr3doc03.txt](https://github.com/scandihealth/lpr3-docs/files/2293003/Lpr3doc03.txt)

**Comment by jonigkeit** [comment]
**RESOLUTION**
Hibernate Issue [HHH-12326 PreUpdate/PrePersist not working for @Embeddable entities](https://hibernate.atlassian.net/browse/HHH-12326) cause a required field / column not to be set.
A workaround has been implemented fixing the issue.
