### ISSUE TITLE
Hibernate ConstraintViolationException error

### ISSUE THREAD

**Issue by CgiMofr** [scandihealth/lpr3-docs#190]
Hi,
When sending the attached hl7 xml we get the following error:

<soap:Fault>
	<faultcode>soap:Server</faultcode>
	<faultstring>javax.ejb.EJBTransactionRolledbackException:
		org.hibernate.exception.ConstraintViolationException: could not
		execute statement</faultstring>
</soap:Fault>

What could be the problem ?

[hl7.zip](https://github.com/scandihealth/lpr3-docs/files/2419607/hl7.zip)

**Comment by TueCN** [comment]
Hi,
I get the same SOAP fault when I try to validate the provided ClinicalDocument on SDS' test environment. 
However, I cannot reproduce the problem on our internal environments. 
This could be because I do not have the previous versions of the set (relatedDocument) and thus am missing the data that causes the interaction that results in the ConstraintViolationException.

We recently fixed a bug found internally that could cause ConstraintViolationException when nullifying/replacing elements. Our fix should be delivered next release (scheduled for Tuesday). 

I hope that bugfix also fixes this issue and think we should wait and see if the problem is still there after Tuesday. Otherwise I need the XML for all previous versions in the set of the attached xml which you can get by clicking the "Vis rådata" button on the 'Vis forløb' UI.

**Comment by CgiMofr** [comment]
Hi,
Attached is a zip file with a version 1 submission which was ok, and a version 2 submission which resultet in the constraintviolation error.
[version1and2.zip](https://github.com/scandihealth/lpr3-docs/files/2427864/version1and2.zip)

**Comment by kbhCGI** [comment]
Was the fix released yesterday?

**Comment by TueCN** [comment]
@CgiMofr I can no longer reproduce the problem on the newest deploy (version 3.7.802). 
Do you still experience the problem?

**Comment by CgiMofr** [comment]
The problem seems to have been solved.
I close the issue.
