### ISSUE TITLE
Myndighedskode 0999 not found in the registry:MYNDIGHED_CODE_NOT_FOUND:0999

### ISSUE THREAD

**Issue by kbhCGI** [scandihealth/lpr3-docs#231]
Hi

I think myndighedkode 0999 is missing.
IF i look in Sundhedsdatastyrelsens kommuneklassifikation.ptf it is existing.
https://sundhedsdatastyrelsen.dk/-/media/sds/filer/rammer-og-retningslinjer/patientregistrering/relaterede/kommuneklassifikation.pdf?la=da

**Comment by TueCN** [comment]
Hi

The pdf document you linked is from 2015 and it is likely that the register has changed since then. 

I looked in the [Myndighedsregister](https://www.cpr.dk/kunder/gratis-download/myndighedsregister-og-udtraeksbeskrivelse/) txt file and could not find the kommune kode `0999` with the text `Uden bopæl eller ukendt bopæl`.

If the kommune is not known, you should use the code `0009` which has the text `Kommune Ukendt`. 
See #208

**Comment by kbhCGI** [comment]
Skat.dk + danmarks statistik + SDS uses 999 as "uden bopæl eller ukendt bopæl".
Are you 100% sure that is 0009 and not 0999 or both?

**Comment by TueCN** [comment]
We do not use any of those as the authoritative source of "Kommune koder". 

We use [CPR's Myndighedsregister](https://www.cpr.dk/kunder/gratis-download/myndighedsregister-og-udtraeksbeskrivelse/) as stated on [art-decor](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.127&effectiveDate=2017-12-11T00:00:00)
> hl7:county | ADXP | 0 … 1 | R | The value of county shall be drawn from value set: 1.2.208.176.1.2.2  CPR Municipality Identifiers.

I am fairly confident 0999 is not a valid code. 
See rule 01.A in [Logisk datamodel og indberetningsregler - Bilag 1 (PDF)](https://sundhedsdatastyrelsen.dk/-/media/sds/filer/rammer-og-retningslinjer/patientregistrering/indberetning-til-lpr3/vejledning-lpr3-bilag-1-model-og-indberetningsregler.pdf?la=da)

> -> kommunekode | MynKod {0009; 0101-0860; 0956-0961} | gyldig kommunekode iht. Myndighedsregisteret
