### ISSUE TITLE
Is ID mandatory for forløbsmarkører?

### ISSUE THREAD

**Issue by metodikamikaelnilsson** [scandihealth/lpr3-docs#236]
The documentation at [art-decor](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.82&effectiveDate=dynamic) states that the ID for a forløbsmarkør is **not** mandatory, whereas the "Vejledning til indberetning til LPR3" (page 55) states that it is. Which is correct?

![Image of Indberetning af forløbsmarkører](https://www.metodika.com/skalpell/ws/temp/lpr3.png)

**Comment by metodikamikaelnilsson** [comment]
I get no validation error when I include a forløbsmarkør that don't have an objectID, so I guess it's not mandatory despite what the "Vejledning.."-documentation says? And furthermore, I guess the mandatory refID to the forløbselement is implicitly set by the fact that the forlforløbsmarkør element resides inside the forløbselement?

**Comment by jonigkeit** [comment]
The confusion stems from inconsistency/coherence between the interface specification and the specification of the "Vejledningen". The problem being the "Vedledningen" not treating how data is communicated as an external concern to it. Ideally the "Vedledningen" would only be using terminology defined by the logical model, but this is not the case.

You're not required to set an id on an episode of care marker act. Keep in mind that if you have to report an observation organizer (resultatindberetning) on the marker you will need an id in order to make the reference.

The "Vejledning" is out of control for DXC, but we will forward the issue on your behalf to SDS.

**Comment by metodikamikaelnilsson** [comment]
Thank you for the clarification.
