### ISSUE TITLE
Missing error details

### ISSUE THREAD

**Issue by ScaAnders** [scandihealth/lpr3-docs#239]
After working on the MTOM protocol we are now trying to create a minimum request that can be submitted to LPR3. We are now in a situation where our request fails (according the status on the response element) but the error list is empty.
Is it possible that you can try executing the request and give a bit more information regarding the specific error?
(Attached are the request and response).
[20181127 raw_request.txt](https://github.com/scandihealth/lpr3-docs/files/2619349/20181127.raw_request.txt)
[20181127 raw_response.txt](https://github.com/scandihealth/lpr3-docs/files/2619351/20181127.raw_response.txt)

**Comment by TueCN** [comment]
Hi. What endpoint are you using? If you are using the [PatientHealthcareValidateReportingService](https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareValidateReportingService) then I think your request has been validated and no issues were found. 

Currently, due to the wording in ITI-41, the validate endpoint **always** returns 
 status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure"`, even when there are no validation issues.

This might change in the future. See #150

**Comment by ScaAnders** [comment]
Yes, that is the one I am using. I really hope you will fix the validation status so that we can trust the status of the response instead of chasing ghosts :)
Can you provide the endpoint where the commit is only done if the document validation completed successfully?

**Comment by ScaAnders** [comment]
Found it: https://scandihealth.github.io/lpr3-docs/testenvironment/index.html
