### ISSUE TITLE
Unexpected error INTERNAL_EOC_NOT_FOUND

### ISSUE THREAD

**Issue by kdjohansson** [scandihealth/lpr3-docs#252]
We are trying to submit a CDA with a reference to another internal episode of care, but the document gets rejected with error INTERNAL_EOC_NOT_FOUND.

Document1.txt is containing a submitted eoc bb665bc7-ff75-5316-ace5-17cb8df6dd52.

Document2.txt is containing the a new eoc with a reference to the first, that results in the folowing error:
INTEGRITY_CHECK|||Internal Episode of Care bb665bc7-ff75-5316-ace5-17cb8df6dd52 not found|||INTERNAL_EOC_NOT_FOUND|||bb665bc7-ff75-5316-ace5-17cb8df6dd52
Location: C56DCEA5-72AF-41DC-95F9-4AE96D425E80^5CD830EC-338A-4AA3-B5FF-EC2952B4A2CF|||//*[local-name()='act' and @classCode='PCPR' and @moodCode='EVN'][child::*[local-name()='id' and @extension='bb665bc7-ff75-5316-ace5-17cb8df6dd52']][child::*[local-name()='templateId' and @root='1.2.208.176.7.1.10.72']][child::*[local-name()='templateId' and @root='2.16.840.1.113883.10.12.301']]

[document1.txt](https://github.com/scandihealth/lpr3-docs/files/2653366/document1.txt)
[document2.txt](https://github.com/scandihealth/lpr3-docs/files/2653367/document2.txt)

**Comment by TueCN** [comment]
[DK Internal Episode Of Care Reference](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.72&effectiveDate=2018-01-04T00:00:00) is a reference to another Episode of Care within the same _document_
> The value of @extension shall be a version 5 UUID to an episode of care within the encompassing CDA document instance.

document2 is referring to an EoC in another document (document1).

If you wish to refer to another EoC in another document, but in the same _set_ you should use [DK External Episode Of Care Reference](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.69&effectiveDate=2017-11-06T00:00:00)

However, document2 is in another set. 
If you wish to refer to another EoC in another document _and_ set, you must use [DK Set External Episode Of Care Reference](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.69&effectiveDate=2017-11-06T00:00:00). 
**Note:** Be aware that, currently, if you create an EoC using lowercase UUID in id/@extension then you cannot reference it using `DK Set External Episode Of Care Reference` since the extension of the referenced EoC must be placed in the externalAct/id/@root of the reference, and roots must be _uppercase_ UUIDs. See #166
