### ISSUE TITLE
Documentation for 1.2.208.176.7.1.22.1

### ISSUE THREAD

**Issue by ScaAnders** [scandihealth/lpr3-docs#253]
I am getting the exception below but I cannot find information regarding the template "hl7:entryRelationship[hl7:templateId[@root='1.2.208.176.7.1.22.1']]". Can you please help me with an art-decor link for the documentation.

`ErrorCode: InvalidDocumentContent
Location: 12edf90e-59a5-5650-bf49-16a39b914509^65922AEA-758A-4573-B60D-EFA110C0DA1D|||/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][2]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][1]/*:act[namespace-uri()='urn:hl7-org:v3'][1]
CodeContext: SCHEMATRON|||(DKProcedureAct): choice (hl7:entryRelationship[hl7:templateId[@root='1.2.208.176.7.1.22.1']] or hl7:reference[hl7:templateId[@root='2.16.840.1.113883.10.12.324']]) does not contain enough elements [min 1x]`

**Comment by TueCN** [comment]
Hi,

Can you attached the input XML document? 
Evaluating the XPath expression against the input document should show you where the problem is 
`/*:ClinicalDocument[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][1]/*:structuredBody[namespace-uri()='urn:hl7-org:v3'][1]/*:component[namespace-uri()='urn:hl7-org:v3'][2]/*:section[namespace-uri()='urn:hl7-org:v3'][1]/*:entry[namespace-uri()='urn:hl7-org:v3'][1]/*:act[namespace-uri()='urn:hl7-org:v3'][1] `

**Comment by ScaAnders** [comment]
[LPR-000000101-m-procudenkontakt.txt](https://github.com/scandihealth/lpr3-docs/files/2662326/LPR-000000101-m-procudenkontakt.txt)

**Comment by ScaAnders** [comment]
True, but as you can see there are no elements with id '1.2.208.176.7.1.22.1' like the error states. So where do I find that documentation?
![image](https://user-images.githubusercontent.com/41738261/49730513-dedb7700-fc78-11e8-837e-320ed166d3bf.png)

**Comment by TueCN** [comment]
Open the `hl7:templateId` sections that are collapsed in your screenshot.

![image](https://user-images.githubusercontent.com/14910711/49730861-ec453100-fc79-11e8-9a44-ca750eb63371.png)

**Comment by ScaAnders** [comment]
Thanks
