### ISSUE TITLE
Adding Service References & Generating classes to use services in VS

### ISSUE THREAD

**Issue by vprxa** [scandihealth/lpr3-docs#262]

**Comment by TueCN** [comment]
Sorry, what exactly is the issue?

**Comment by johonovax** [comment]
Hi Scandihealth,
I am trying to add the following URLs as Service References in Visual Studio:

https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareSaveIfNoErrorsReportingService?wsdl

https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareReportingService?wsdl

https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareValidateReportingService?wsdl

The first URL resolves a method called DocumentRepository_ProvideAndRegisterDocumentSetb and the remaining cannot be resolved.

I have also tried to generate classes using the wsdl.exe but they too result in error.

Am I using these services correctly?

Do you have documentation for the service methods i.e. request and response objects? I ask because the https://scandihealth.github.io/lpr3-docs/ provides service URLs and sample soap requests but doesn’t document the DocumentRepository_ProvideAndRegisterDocumentSetb method resolved. It contains types such as SubmitObjectsRequest, IdentifiableType, SlotType1 which aren't apparent.

Thank you,
Joe

**Comment by vprxa** [comment]
Hi @TueCN ,
Thank you for the information.
Joe
