### ISSUE TITLE
Error when replacing episode

### ISSUE THREAD

**Issue by Smp-xmedicus** [scandihealth/lpr3-docs#263]
When I try to replace an episode, because I have changed the Episode Label, I get 

>  <soap:Text xml:lang="en">java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.dxc.lpr.ejb3.persist.lpr3.ForloebElementEntity.cdaDocument -&gt; com.dxc.lpr.ejb3.persist.lpr3.CdaDocumentMetadataEntity</soap:Text>

.
Attached Full Document, Clinical Document and error response
[Error.zip](https://github.com/scandihealth/lpr3-docs/files/2697924/Error.zip)

**Comment by TueCN** [comment]
Hi,
In the future, please attach all ClinicalDocuments needed to reproduce the error. The ClinicalDocument you attached has references to other existing eoc/encounter/condition observations.

After a bit of trial and error I have successfully reproduced the error, but the input XML involved is not really a meaningful submission (it should not pass integrity checks and thus it should be prevented from being saved).

Your XML contains an [DK External Episode Of Care Replacement Reference](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.120&effectiveDate=2017-09-13T00:00:00), but your document does not have a [DK RelatedDocument](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?section=templates&id=1.2.208.176.7.1.10.111&effectiveDate=2018-01-04T00:00:00) element, which means your document is the first document in the set (and thus the EoC referenced cannot already exist in the set)

I have reproduced the error by first creating an eoc+encounter+ConditionObservation in a separate set and then inserting only their extensions in the reference parts of your document. 

This should give INTEGRITY_CHECK errors because the elements do not exist in the set, but instead it gives a IllegalStateException. We will look into it, but it has not high priority as the input XML is invalid to begin with and cannot be saved.
