### ISSUE TITLE
Hibernate error after upgrade

### ISSUE THREAD

**Issue by MichaelEsmannSSE** [scandihealth/lpr3-docs#285]
After todays upgrade (21-01-2019) we are getting this error that we didn't get before in one of our tests:
`<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/><soap:Body><soap:Fault><soap:Code><soap:Value>soap:Receiver</soap:Value></soap:Code><soap:Reason><soap:Text xml:lang="en">org.hibernate.PropertyAccessException: Could not set field value [Kvinde] value by reflection : [class com.dxc.lpr.ejb3.persist.lpr3.ForloebElementEntity.patientKoen] setter of com.dxc.lpr.ejb3.persist.lpr3.ForloebElementEntity.patientKoen</soap:Text></soap:Reason></soap:Fault></soap:Body></soap:Envelope>`
The error occurs when trying to delete a procedure. I can give you the series of documents that we are sending, but I hope you can identify the problem from the soapfault.

**Comment by MichaelEsmannSSE** [comment]
The problem seems to have disappeared now. I will close the issue.

**Comment by MichaelEsmannSSE** [comment]
Now we are getting a similar error

`<faultcode>Receiver</faultcode>
                    <faultstring>org.hibernate.PropertyAccessException: Could not set field value [Mand] value by reflection : [class com.dxc.lpr.ejb3.persist.lpr3.ForloebElementEntity.patientKoen] setter of com.dxc.lpr.ejb3.persist.lpr3.ForloebElementEntity.patientKoen</faultstring>`

So I reopen this defect again

**Comment by MichaelEsmannSSE** [comment]
... and now I also get the original error again

**Comment by Remcovanderwerf** [comment]
Hi,

FYI:
Today I also encounted the same error as mentioned in the first comment (sending to the LPR3 test environment on "savewitherrrors".

Kind regards,

Remco van der Werf
Enovation | The Netherlands
Contractor: Region Syddanmark

**Comment by TueCN** [comment]
Yes unfortunately the issue was not resolved with latest deploy. 
We are still investigating. 
(the current hypothesis is that it might be related to "forløbsreferencer" (episode of care links)

**Comment by TueCN** [comment]
**Update**: The current hypothesis is that the issue is related to the infrastructure of the TEST environment.   

TEST is a single server environment with all deployments co-existing in the same server instance. This leads to problems with the shared cache, when one deployment unit creates a cache entry and another deployment unit acces that same cache entry. 
We believe that this can lead to strange behavior such as what is experienced on this issue and possible also #280.

This problem should not be present on PROD which is a multi-server environment with distributed cache, because on PROD, the deployments are distributed across servers and do not directly access the same cache entries.

Hopefully SDS will upgrade the TEST environment infrastructure to be a multi-server environment to better match the PROD environment infrastructure. 
Meanwhile, we will work on a change for the single-server infrastructure that fixes this issue 
(but this fix has less priority than issues affecting PROD).

**Comment by Remcovanderwerf** [comment]
Hi,

apparantly this issue is still not fixed as it has occured again this morning.

```
Response-Code: 500
Encoding: ISO-8859-1
Content-Type: multipart/related; type="application/xop+xml"; boundary="uuid:e12a0372-7f71-4d4d-9734-f90ceedb9e95"; start="<root.message@cxf.apache.org>"; start-info="application/soap+xml"
Headers: {connection=[close], Content-Language=[da-DK], Content-Length=[1282], content-type=[multipart/related; type="application/xop+xml"; boundary="uuid:e12a0372-7f71-4d4d-9734-f90ceedb9e95"; start="<root.message@cxf.apache.org>"; start-info="application/soap+xml"], Date=[Mon, 25 Feb 2019 12:06:13 GMT], Strict-Transport-Security=[max-age=31536000; includeSubDomains], X-Powered-By=[Servlet/3.0]}
Payload: --uuid:e12a0372-7f71-4d4d-9734-f90ceedb9e95
Content-Type: application/xop+xml; charset=UTF-8; type="application/soap+xml"
Content-Transfer-Encoding: binary
Content-ID: <root.message@cxf.apache.org>

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><Action xmlns="http://www.w3.org/2005/08/addressing">urn:ihe:iti:xds-b:2007:DocumentRepository_PortType:DocumentRepository_ProvideAndRegisterDocumentSet-b:Fault:EJBException</Action><MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:63c70c8f-35c8-4592-acdf-83ea29717643</MessageID><To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To><RelatesTo xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:3ec7e6e9-8c40-4743-b50a-70598a6a20bf</RelatesTo></soap:Header><soap:Body><soap:Fault><soap:Code><soap:Value>soap:Receiver</soap:Value></soap:Code><soap:Reason><soap:Text xml:lang="en">org.hibernate.PropertyAccessException: Could not set field value [Kvinde] value by reflection : [class com.dxc.lpr.ejb3.persist.lpr3.ForloebElementEntity.patientKoen] setter of com.dxc.lpr.ejb3.persist.lpr3.ForloebElementEntity.patientKoen</soap:Text></soap:Reason></soap:Fault></soap:Body></soap:Envelope>
--uuid:e12a0372-7f71-4d4d-9734-f90ceedb9e95--
```

**Comment by Remcovanderwerf** [comment]
Hi @TueCN ,

Currently on the _test_ environment we are experiencing these above issues.
This has come to a point where it occurs quite frequently.
The strange thing is the following:

Yesterday around 16:44 we tried submitting the following document.
[CDA_16-43-32_RSYD_XXXXXXXXXX_2_Indberetninger.txt](https://github.com/scandihealth/lpr3-docs/files/2912016/CDA_16-43-32_RSYD_XXXXXXXXXX_2_Indberetninger.txt)

In our sending application we kept on receiving this error showed in my previous comment.
After midnight (around 00:00:41) our application did another attempt to submit this same document and it did come through.
[Response_00-00-41_RSYD_XXXXXXXXXX_2_Indberetninger.txt](https://github.com/scandihealth/lpr3-docs/files/2912025/Response_00-00-41_RSYD_XXXXXXXXXX_2_Indberetninger.txt)


Today we are trying to submit version 3 of the document
[CDA_12-28-29_RSYD_XXXXXXXXXXX_3_Indberetninger.txt](https://github.com/scandihealth/lpr3-docs/files/2912028/CDA_12-28-29_RSYD_XXXXXXXXXXX_3_Indberetninger.txt)

but it does not get through either.  We have the suspicion it has something to do with the content of the document rather than server specs on this test enviroment.
Ofcourse I would like to ask you to investigate to either confirm or deny this issue being content related.

Some more examples of documents which do not get through for now but possibly do after midnight:
[CDA_10-42-23_RSYD_XXXXXXXXXX_3_Indberetninger.txt](https://github.com/scandihealth/lpr3-docs/files/2912057/CDA_10-42-23_RSYD_XXXXXXXXXX_3_Indberetninger.txt)
[CDA_16-28-51_RSYD_XXXXXXXXXX_2_Indberetninger.txt](https://github.com/scandihealth/lpr3-docs/files/2912058/CDA_16-28-51_RSYD_XXXXXXXXXX_2_Indberetninger.txt)

Looking forwarding hearing from you!

Kind regards,

Remco van der Werf
Enovation | The Netherlands
Contractor: Region Syddanmark

**Comment by MichaelEsmannSSE** [comment]
Today we have experienced this error quite often.  And it is disturbing our tests quite a lot. So we agree with the previous comments that you should give this defect higher priority.

**Comment by RasmusThernoe** [comment]
Any news on this defect?

We are impeded by this defect in testing issues in LPR3 reporting - the defect occurs very often when updating reporting entities.

**Comment by TueCN** [comment]
In coordination with SDS, we are currently focusing our efforts on #322. 
After that, I think #318 also has higher priority (if it turns out not to be the same root cause). 
We will eventually get to this issue :)

**Comment by TueCN** [comment]
Cache expiration has been lowered from 24 hours to 1 hour, until this issue is resolved. 
This should ease some of the inconveniences this issue causes.

**Comment by TueCN** [comment]
With todays update, caching will be entirely disabled on **TEST**, until a proper solution is ready. 
Internal testing shows this suppresses the issue.

This means that performance on TEST will worsen slightly (but still be acceptable) until a proper solution is deployed.

**Comment by MichaelEsmannSSE** [comment]
We have not seen this error in the last weeks so I close the issue
