### ISSUE TITLE
Error: Author/custodian is not matching registered relation

### ISSUE THREAD

**Issue by Marc-Petersen** [scandihealth/lpr3-docs#290]
Then we attempt to submit CDAs for privately owned institutions (selvejende institutioner), we're rejected based on location codes, which we believe are correct.
Error:
![image](https://user-images.githubusercontent.com/44767916/51682117-dc459e80-1fe6-11e9-920a-f3eac1ddda2b.png)
Message:
![image](https://user-images.githubusercontent.com/44767916/51682130-e49dd980-1fe6-11e9-9e89-a5c6754f7552.png)

In this message, we are sending the CVR ID of HOG Hospicegården Filadelfia and the SOR ID, we believe to be correct.

Is there a possibility, these facilities are mismapped within SDS?

**Comment by TueCN** [comment]
CUSTODIAN_NOT_FOUND error occurs when the the custodian CVR number and author SOR id is not registered as being "connected", in the LPR administration module, by a LPR administrator.
To fix this issue here and now, you can ask SDS to register the relation.

However, we are working on an update to this "authorization check" that eliminates this registration altogether. 
In the future there will not be any need to be registered in the administration module. 
Instead LPR checks that the CDA "author" SOR id identifies a unit in the SOR registry that has a SOR institution owner with the CVR number provided in the medcom:CareProviderID SAML attribute of the SOAP envelope.

This way LPR checks that the sender is authorized to report on behalf of the author SOR unit.
(LPR assumes that the sender is authorized to report on behalf of a SOR unit when the sender is authenticated (via XML signature) as the instiution owner of the SOR unit)
