### ISSUE TITLE
LPR3 11101 triggering but can't see why

### ISSUE THREAD

**Issue by RegHThrane** [scandihealth/lpr3-docs#305]
We are seeing our end user are getting LPR3 error 11101 stating that a procedure should be in one of the following lists Proc.opr, Proc.act or Proc.und. Our problem is that we a can't seem to understand why, as neither Proc.act or Proc.und is official SDS codelists. What we can find on those two lists is that they both have a comment of "CDA-betinget kategori; anvendes ikke i indberetningen". What does this mean and why are we seeing these errors?

**Comment by TueCN** [comment]
The rule 11.101 has not been updated since the decision to not use proc.act and proc.und was taken. 
The rule should be correct regardless, as it will not generate a validation error if the SKS code is in the list proc.opr.
See https://scandihealth.github.io/lpr3-docs/faq/index.html#i-want-to-report-a-procedure-which-template-should-i-use
>UPDATE To ease integration Sundhedsdatastyrelsen has decided that proc.oper urn:oid:1.2.208.176.2.4.20 will contain values for Act, Procedure, and Observation while the two other valuesets proc.act urn:oid:1.2.208.176.2.4.19 and proc.und urn:oid:1.2.208.176.2.4.21 will be empty

You can ask SDS (the rule authors) to update the error description of rule 11.101 to remove the mentions of proc.act and proc.und.
