### ISSUE TITLE
Response time (out) 

### ISSUE THREAD

**Issue by Remcovanderwerf** [scandihealth/lpr3-docs#315]
Hi,

just for the final configuration:
What is the maximum response time from LPR3 so I can configure the time-out time of our sending application appropriately. 

I have been reading 5 minutes and 10 seconds in another issue (#189 ) but I thought that was marked as invalid.

Thank you in advance!

Remco van der Werf
Enovation, the Netherlands
Contractor: Region Syddanmark

**Comment by TueCN** [comment]
Hi,

Please read [CONTRIBUTING.md#service-levels-and-performane](https://github.com/scandihealth/lpr3-docs/blob/master/CONTRIBUTING.md#service-levels-and-performane)

**Comment by KirstenLHSDS** [comment]
Hi, 
I will be happy to help. 
The simple question may not be quite as simple to answer, but current best answer is based upon performance measurements run as part of the performance validation. 
First thing to mention is though, that average response time may increase during time, if a patient has many encounters linked to the same 'forløbselement'. Thus your client may need to monitor, how many time out cases they experience and if this number has a growing trend. 
With this in mind, it seems that a time out set between 10 and 15 seconds will be a reasonable value. I hope this is a usable answer, otherwise feel free to get back.

**Comment by jonigkeit** [comment]
Currently, the internal HA proxy is configured with a timeout of 60 seconds for request to `/cda-ws/*` for both client and server connections, so that should be an upper limit on what you should expect.

**Comment by Remcovanderwerf** [comment]
Hi,

thank you for the response. 
I will  configure the timeout on our sending application around 70s.

Kind regards,

Remco van der Werf
