### ISSUE TITLE
DK Internal Episode Of Care Reference - Extension

### ISSUE THREAD

**Issue by vprxa** [scandihealth/lpr3-docs#338]
Hi Scandihealth,
The DK Internal Episode Of Care Reference > id > extension on art-decor says:

> The value of @extension shall be a version 5 UUID to an episode of care within the encompassing CDA document instance.

[http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.72&effectiveDate=dynamic](http://lpr-art-decor.westeurope.cloudapp.azure.com:8080/art-decor/decor-templates--lpr-?id=1.2.208.176.7.1.10.72&effectiveDate=dynamic)

Which uuid does the extension refer to please? An id root within the DK Episode Of Care Act?

Thank you,
Joe

**Comment by TueCN** [comment]
Hi,
the `DK Internal Episode Of Care Reference > id > extension` attribute must match a 
`DK Episode Of Care Act > id > extension` attribute within the same ClinicalDocument

Does this answer your question?

**Comment by vprxa** [comment]
Hi @TueCN,
Yes thank you. I ask because I am creating the DK Episode Of Care Act > id > extension as follows:

```
var episodeOfCareAuthorUUID = UuidUtil.NewNamespaceUuid(new Guid("fe537378-31eb-5036-91da-72ed4eecae10"), _sorId);

var episodeOfCareUUID = UuidUtil.NewNamespaceUuid(episodeOfCareAuthorUUID, _setId.ToString());
```

The generated episodeOfCareUUID is always the same, and therefore I receive an error to tell me the Episode of Care already exists:

> "INTEGRITY_CHECK|||Episode of Care Marker 12ac4d84-09ff-5eea-830f-4f1286a8561c already exists in the registry|||EOC_MARKER_ALREADY_EXISTS|||12ac4d84-09ff-5eea-830f-4f1286a8561c"

```
The value of @extension shall be created as a version 5 UUID in the following manner.
Create an AuthorUUID in the namespace: fe537378-31eb-5036-91da-72ed4eecae10 with the SOR identifier of the author as the name.
Create the EpisodeOfCareUUID in the AuthorUUID namespace with the local unique identifier of the episode of care.
```

Does the local unique identifier refer to the DK Episode Of Care Act > id > root?
Did I misinterpret something?

Thank you,
Joe

**Comment by KirstenLHSDS** [comment]
We will take this to DXC, to continue the dialog. Github will be closed

**Comment by vprxa** [comment]
Hi @KirstenLHSDS,

Where might I expect to receive a reply?

Thank you,
Joe

**Comment by KirstenLHSDS** [comment]
Hi Joe

Please send your contact email to me, khansen@sundhedsdataprogrammet.dk, and then I will add you to the case.

**Comment by vprxa** [comment]
Hi @KirstenLHSDS,

Much appreciated, you can reach me at joho@novax.dk

Thank you,
Joe

**Comment by TueCN** [comment]
Without knowing the implementation details of your code snippet, I think the problem is you are using the "static" `_setId.ToString()` to generate the extension part of the id, which means that your code always generates the same extension each time it is called with same setId, and thus if you have 2 objects in the set, you get the error that it already exists in the registry. 

Extensions must be globally unique in LPR, that is why you must use version 5 UUIDs that encodes some (locally) unique id using your SOR identifier, which makes it globally unique in LPR.

So, instead you should use some value that is (locally) unique _per object_ such that each object gets its own unique extension.

Example: 
var episodeOfCareUUID = UuidUtil.NewNamespaceUuid(episodeOfCareAuthorUUID, **yourEocLocallyUniqueId**);

**Note**: The error you pasted is actually related to an `Episode of Care Marker`, not an `Episode of Care`. I assume it is the same problem.
