### ISSUE TITLE
Demo project

### ISSUE THREAD

**Issue by mhylle** [scandihealth/lpr3-docs#36]
As we are trying to get the first calls through to the service we are running into several technical issues in regards to the webservice itself. 
In order to minimize the amount of guess work needed to get it to work it would be very helpfull if we had a demo project that was able to call the test webservice with a simple hardcoded document. This way we would have a reference on what is needed to do the call.

**Comment by jkiddo** [comment]
Can you supply stacktraces/logs og your traffic?

**Comment by mhylle** [comment]
We will be sending traces/logs in another issue. 
This issue was also just a reminder to @jonigkeit that he promised us a sample project  :)

**Comment by MartinHylleberg** [comment]
Please do not forget this one, although we are implementing DGWS it would still be a help to have the demo project.

**Comment by rsagner** [comment]
We would also like to see a demo project that can act as an example on how to submit a document in its most simplest form. Will that be available? If not can you recommend a client framework to use as a good starting point?

**Comment by jkiddo** [comment]
In order to supply a demo project that is agnostic towards implementation specific languages we can provide a SoapUI project that will enable you to see a valid and well-formed sample request that you yourself can use and try to send requests with. Bear in mind, that the DGWS tokens that are used in the sample expires within a day or so meaning that you yourself will have to regenerate these from time to time. Also, please remember that the interfaces and data models used are all based on international standards. As such, the IHE XDR WSDL is only extended with the required DGWS headers (a profile on WS-Security/WSI Basic profile 1.1) and these headers are also expressed in a standardized way - meaning that ordinary WSDL-to-code tools can be used. The data model follows the HL7 CDA and no extensions are made - meaning that the regular HL7 CDA xsd's can be used for generation of code.

**Comment by rsagner** [comment]
I agree @jkiddo it might hard making an example that works for all. That said it would be great with some suggested frameworks/modules for some different languages and some example code that shows how to implement a client. We are currently looking into implementing the backend (client side backend) in node.js and are trying to locate which modules to use. As I understand we need a soap client with support for mtom/xop and ws-security that also supports injecting special headers. I assume you have build some test clients, what platform/framwork did you use?

**Comment by jkiddo** [comment]
@rsagner - sounds like you are on the right track. Our test clients are written in Java - using the ordinary JAX-WS implementations and we've looked at the DGWS reference implementations as well

**Comment by MartinHylleberg** [comment]
We feel that having a SoapUI project would be a great help even though the security information would be out of date. 
Having a reference would eliminate a lot of guess work, so we would be glad if such a one was provided.

**Comment by cjonigkeit-csc** [comment]
See https://github.com/scandihealth/lpr3-cda/tree/master/soap-ui.
