### ISSUE TITLE
UUID mapping to LPR3

### ISSUE THREAD

**Issue by DaveSS** [scandihealth/lpr3-docs#40]
We would like to verify that our understanding of how the use of UUIDs in the CDA document conform to the SDS LPR3 data model.

Specifically, the fact that multiple UUIDs in LPR3 documents might be used for the same clinical concept on our end (like a diagnosis or a result report). For example, a diagnosis for a patient might be associated with 2 separate Kontakts. Therefore, the diagnosis would need to be sent in 2 separate condition entries, each with a unique UUID and a reference to a single Kontakt using that diagnosis. So in the LPR3 data model, there are 2 separate diagnoses that must be updated individually, even though they might be related to a single concept on our end.

**Comment by jonigkeit** [comment]
That is correct.
The internal data model is not fully normalized, e.g. condition (Diagnose) and encounter (Kontakt).
This is primarily do reduce the complexity of the CDA structure while allowing a condition to be modified without having to report the entire encounter again. Otherwise there has to be an element of indirection (relationship entity) that binds an encounter and a condition together, allowing encounters to share conditions and still supporting modification of a condition without resubmitting the entire encounter.
I suppose one would can use a composite key (encounter and condition) to generate id's for denormalized conditions.

**Comment by DaveSS** [comment]
Just to follow up, we’re wondering how the CDA model is able to track over-time changes as a specific diagnosis traverses from one kontakt to another. I included a file with screenshots and a specific example with questions.
[OverTimeExample.pdf](https://github.com/scandihealth/lpr3-docs/files/1741897/OverTimeExample.pdf)

**Comment by cjonigkeit-csc** [comment]
Moved to #43.

**Comment by cjonigkeit-csc** [comment]
You would help us greatly by creating separate issues for new questions.
